### ISSUE TITLE
possibility to specify target folder

### ISSUE THREAD

**Issue by tinect** [own3d/bunny-cli#1]
Thank you for the cli and the github-action.

I'd like to build preview-builds on to bunny.net whenever a PR is being added.

It would be great to have an option to specify a target folder.
Is there an option?

**Comment by ki11roy** [comment]
https://github.com/own3d/bunny-cli/pull/4 will possibly solve this.

**Comment by ghostzero** [comment]
Merged #4, thanks for the contribution!
